### ISSUE TITLE
Version 4.5.0 PNG and SVG issues (laser), had to revert to version 4.4.0

### ISSUE THREAD

**Issue by siffalo** [Snapmaker/Luban#1884]
After installing the 4.5.0 upgrade, the workflow for laser was radically broken compared to version 4.4.0 and several previous versions, despite no related changes being mentioned in the release notes.

1. Related to/seconding issue 1877:  Importing a 320mm x 350mm SVG comes in at roughly twice the size, but the contents of the SVG are quite small in comparison--scaling down to the correct dimensions really doesn't help correct the contents.
2. Importing a PNG, then switching to Vector stretches the dimensions of the file radically and disproportionately.  Non-Vector modes  B&W, Greyscale and Halftone all have the proper dimensions.

Had to revert to version 4.4.0, as this area of the upgrade is pretty much useless.  

Thanks.

**Comment by parachvte** [comment]
The issue is related to [commit](https://github.com/Snapmaker/Luban/commit/e83ffcec408bf8f12578cbd69b18cd8bb8be037d#diff-f89d9f1d28a4ca76b8e633072f3f5e3bdb94ec31c7d13828017f5377c961d648), which tried to recalculation actual bounding box of shapes in SVG, and re-wrap all shapes in a new bounding box.

But this change is not complete, width & height are not re-calculated too. Also several display issue should be resolved due to size ratio changed, so I'm reverting this change back to v4.4.0 version.

We will release a patch later this week (v4.5.1).
