### ISSUE TITLE
Bug: Artisan - Laser Mode - Preview Image turned around

### ISSUE THREAD

**Issue by mmack** [Snapmaker/Luban#1914]
If i do a Camera Capture in Luban 4.5.1 with the Artisan, the Image is upside Down. Look at my example Image, the Iphone is placed with the bottom towards the door. 

![snapmaker](https://user-images.githubusercontent.com/100767/216760313-398fb919-f4a6-4227-9f5f-a02fa45eb08d.PNG)

**Comment by parachvte** [comment]
You might need a calibration for the camera. The calibration points affect the preview.

**Comment by mmack** [comment]
I did all the calibrations the Artisan forces me to do. Including the camera calibration.

**Comment by parachvte** [comment]
Sorry for inconvenience.

The upside down capture image could be software problem, or hardware problem. And since we don't have a way to export the camera calibration configs we might need to recheck this can be re-produced on our side.
I would suggest you contact support@snapmaker.com for direct technical support.
