### ISSUE TITLE
Broke: Copy , & Paste in Console

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Luban#254]
This is likely on your list already, mentioned by a lot of people. Just want to track it.

**Comment by tonejaco** [comment]
How hard would it be to just start with being able to copy the text in the console window?
I get so tired of having to transcribe the matrix data. Especially with a 5 x 5 or larger matrix!! :-)

**Comment by tonejaco** [comment]
So Cut, Copy & Paste does work on the Command line of the Console on the Mac too. "Select All" doesn't work. And there is an anomaly about selecting in that command line, it seems the region where that selection works doesn't match the actual size of the command line. It's like it only works in the top half of that region.  Pasting into the command line doesn't want to include any "returns" that are in the copied text. So there are a few things besides copying in the console window that need to be fixed.

**Comment by tonejaco** [comment]
More on selection region, it appears you can click anywhere in the Console window and it will insert the cursor into the command line. It shouldn't work that way.

**Comment by tonejaco** [comment]
The version uploaded to the forum doesn't have the funny region problem with the Command line in the console.

**Comment by tonejaco** [comment]
I changed the title to "Broke" because most of it is there, it just doesn't all work right.

**Comment by tonejaco** [comment]
A paste into the command line should probably check syntax and refuse to paste if it doesn't pass. Of course that could be a whole new feature in itself. It should be able to paste multi line gcode commands. (including the line returns)

**Comment by cocojoe** [comment]
@tonejaco I had a quick look here, only just noticed Luban source was available 😄  The console functionality is provided by https://github.com/xtermjs/xterm.js 

It's using an older 3.x version, a switch to the new major of this lib 4.x may improve things in general. The issue seems to be dependant on which browser is rendering Luban. If I run this under Windows and use Edge browser, I can use ctrl+c/ctrl+v to successfully copy/paste from the console to notepad. It didn't work under Firefox or Chrome.

https://github.com/xtermjs/xterm.js/issues/2478

**Comment by tonejaco** [comment]
Are copying from the display portion of the console window or just the command line portion?

**Comment by cocojoe** [comment]
This was for the display portion of the console.

**Comment by cocojoe** [comment]
@tonejaco I've raised a PR for this and included a video.

**Comment by cocojoe** [comment]
I removed the behaviour of clicking in the console window will autofocus onto the command line. In retrospect, this might have been the root cause issue around copy/paste from the console. As if the focus is switched to the CLI then the window you wanted to copy/paste is now out of focus.

The reason I believe it was done like this is the console window is a fully functional terminal. You can enter commands directly into it. However, that would defeat the point of having the CLI box I presume and it's not as clean in some ways. So that's why it would shift focus from window to CLI box to avoid this happening.

**Comment by cocojoe** [comment]
I ran a test on this by allowing the console window to stay in focus and avoid using CLI box.
I could paste in multi-line commands e.g

```
G
M
```

And it works 👍 

The "Feature" fix here, depending on the path the developers want to go down. Is to remove the CLI box and use the console window as it was designed to be used.

**Comment by tonejaco** [comment]
Sounds Great!
I like that the up & down arrows work for scrolling to previous commands if you want to re-execute them.

**Comment by tonejaco** [comment]
Do you think this is related to the controller not echoing when connected via WiFi? #251

**Comment by parachvte** [comment]
With #275 merged, this issues can be closed.

**Comment by tonejaco** [comment]
I just noticed this today, something to check if it still exists once this release is out. When the terminal window is expanded to fill the region from top to bottom, the text that was in the Workspace shows through to the console as if the window was tansparent.
![Screen Shot 2020-04-10 at 3 48 18 PM](https://user-images.githubusercontent.com/37938299/79028535-92929680-7b4d-11ea-97c7-138d068e0b4f.png)

3.3.3 Snapmaker Luban
This on a Mac with 10.14.2 MacOS.

**Comment by parachvte** [comment]
It's still there.

**Comment by tonejaco** [comment]
Does this warrant a new issue? It's not a copy/paste thing.

**Comment by parachvte** [comment]
It's minor issue that was fixed in #290

**Comment by tonejaco** [comment]
In 3.5, selecting copy from the Edit menu works, doing a ctrl-C doesn't.

**Comment by tonejaco** [comment]
Works ok on my Mac. One thing I noticed on the PC was that when you did the copy command from the menu, the selection went away, that is the highlighting of the selection. Doesn't do that on the Mac.

**Comment by tonejaco** [comment]
Time to close.

**Comment by oldztimer** [comment]
I just updated to the latest Luban 3.15.1 on MacOS 11.4

Copy from the console does not work (again). (I've tried multiple copy key combos: Cmd+C, Ctrl+C, Ctrl+Shft+C)
Paste to the console does not work.

I don't get any contextmenu or app menus to trigger copy/paste by other means.

**Comment by wri-matt** [comment]
Confirmed. I am seeing the same results as @oldztimer . No ability to copy from the console window, which makes manually leveling the bed TEDIOUS. No keystrokes, no Edit menu, no context menu. This needs to be re-opened (at least for the Mac).
