### ISSUE TITLE
Camera capture calibration goes wrong

### ISSUE THREAD

**Issue by pauserratgutierrez** [Snapmaker/Luban#789]
I do the 4 corner calibration the best I can.

Photo with 4 corner calibration:
![4 points](https://user-images.githubusercontent.com/73240206/108778691-07a06c00-7566-11eb-93b1-5fd10604a57d.jpg)

My camera captures the bed this way:
![bed](https://user-images.githubusercontent.com/73240206/108778746-256dd100-7566-11eb-93a5-b1e624aa0b49.jpg)

In addition, why my 4 corner calibration image is turned?

**Comment by ldp7** [comment]
In the first calibration result image, the background image you got is tilted. The screen transfers the image via Bluetooth to Snapmaker Luban, which displays it directly without any processing.

Could you please send me the source image of it so that we can troubleshoot it?
On your computer, check the images in a folder named "Temp", and they are generated by the camera directly. You need to send us the jpg files with file names starting with calibration, and here is an image for your reference:


For Windows OS: C:\Users\admin\AppData\Roaming\snapmaker-luban\Tmp
admin is PC's username

For macOS: /Users/admin/Library/Application\ Support/snapmaker-luban/Tmp
admin is PC's username

**Comment by ldp7** [comment]
![Clibration image](https://user-images.githubusercontent.com/62584712/108793027-92608580-75bd-11eb-8653-1434bb0b30a8.png)

**Comment by jane-rose** [comment]
As for the second result image, you have to use farmware version below 1.9.0 or waiting for the luban version 3.14.0 to solve the mismatch in the third column. Sorry for that happened.

**Comment by paauserrat** [comment]
Hi. I did the calibration again as in that folder I had nothing (could be because I started the machine again).

I have the Snapmaker 2.0 a250

The photos on the "tmp" directory:
![calibration_32261083](https://user-images.githubusercontent.com/73240206/108838637-35bc9500-75d4-11eb-8f5c-07af318f8987.jpg)
![calibration_32985036](https://user-images.githubusercontent.com/73240206/108838639-36552b80-75d4-11eb-913c-ddf22ff345f6.jpg)
![calibration_31135009](https://user-images.githubusercontent.com/73240206/108838640-36552b80-75d4-11eb-8090-c88a64dd8b40.jpg)

If you need them too, I did photos of my calibration proces:

First time I run 4 point calibration the points appear where they want. Also, when I click reset they go to this position.
![First time calibration points need to be aligned](https://user-images.githubusercontent.com/73240206/108838762-5dabf880-75d4-11eb-973a-8ab0510687d0.jpg)

Then I align the points:
![I align the points the best I can](https://user-images.githubusercontent.com/73240206/108838847-7f0ce480-75d4-11eb-92a8-47193a14f7f5.jpg)

The calibration is done:
![calibration done](https://user-images.githubusercontent.com/73240206/108838867-8502c580-75d4-11eb-972c-014162324490.jpg)

The photo displayed as background:
![bed2](https://user-images.githubusercontent.com/73240206/108838880-8df39700-75d4-11eb-9408-0b781cc52e1c.jpg)

For instance, if I try to engrave something in a specific position of the background my machine doesn't go there. Why?

**Comment by jane-rose** [comment]
Could you send your engraving operation steps and engraving result photos?

**Comment by lephiloux** [comment]
The problem for me is that background is not centred on the coordinate system of the grid 
![Screenshot_20210402_211445](https://user-images.githubusercontent.com/2427071/113446697-a12a2b80-93f8-11eb-9827-397df2a76f8b.png)

**Comment by paauserrat** [comment]
Please, this is important. I'm running luban 1.14 and my laser doesn't capture the bed correctly.

**Comment by jane-rose** [comment]
> Please, this is important. I'm running luban 1.14 and my laser doesn't capture the bed correctly.

The abnormal phenomenon is that the photo on calibration page is tilted, can you send the result of your carving?

**Comment by ldp7** [comment]
Please refer to this video and send us those images in the "temp" folder. Thank you in advance.

How to troubleshoot the Camera capture feature if the images are titled:
https://drive.google.com/file/d/1NcqDwbc0LxLScpjfv-MScim7xJxyKJQX/view?usp=sharing

You need to check the images in a folder named "temp", which are generated by the camera directly.
Windows OS: C:\Users\admin\AppData\Roaming\snapmaker-luban\Tmp
admin is PC's Profile
Mac Os: /Users/admin/Library/Application\ Support/snapmaker-luban/Tmp
admin is PC's Profile

**Comment by ldp7** [comment]
@paauserrat  

We want to see the calibration image after you click the "Confirm" button in Snapmaker Luban.

**Comment by paauserrat** [comment]
> Hi. I did the calibration again as in that folder I had nothing (could be because I started the machine again).
> 
> I have the Snapmaker 2.0 a250
> 
> The photos on the "tmp" directory:
> ![calibration_32261083](https://user-images.githubusercontent.com/73240206/108838637-35bc9500-75d4-11eb-8f5c-07af318f8987.jpg)
> ![calibration_32985036](https://user-images.githubusercontent.com/73240206/108838639-36552b80-75d4-11eb-913c-ddf22ff345f6.jpg)
> ![calibration_31135009](https://user-images.githubusercontent.com/73240206/108838640-36552b80-75d4-11eb-8090-c88a64dd8b40.jpg)
> 
> If you need them too, I did photos of my calibration proces:
> 
> First time I run 4 point calibration the points appear where they want. Also, when I click reset they go to this position.
> ![First time calibration points need to be aligned](https://user-images.githubusercontent.com/73240206/108838762-5dabf880-75d4-11eb-973a-8ab0510687d0.jpg)
> 
> Then I align the points:
> ![I align the points the best I can](https://user-images.githubusercontent.com/73240206/108838847-7f0ce480-75d4-11eb-92a8-47193a14f7f5.jpg)
> 
> The calibration is done:
> ![calibration done](https://user-images.githubusercontent.com/73240206/108838867-8502c580-75d4-11eb-972c-014162324490.jpg)
> 
> The photo displayed as background:
> ![bed2](https://user-images.githubusercontent.com/73240206/108838880-8df39700-75d4-11eb-9408-0b781cc52e1c.jpg)
> 
> For instance, if I try to engrave something in a specific position of the background my machine doesn't go there. Why?

I already uploaded them here. Didn't I? Do you want me to do the calibration again and send them? Do you need the image name too?

**Comment by pauserratgutierrez** [comment]
Hi, I still have this issue. May I contact sales service?

**Comment by jane-rose** [comment]
Hi. You can contact [support service]([support@snapmaker.com](mailto:support@snapmaker.com))(may a remote video to reproduce and solve your problem). The photo displayed as background seems correct. By the way, the  problem is `if u try to engrave something in a specific position of the background your machine doesn't go there.`? And what firmware version and luban version you are using now.

**Comment by sublime24** [comment]
Hello, I have the same issue was this ever resolved?

**Comment by jane-rose** [comment]
> Hello, I have the same issue was this ever resolved? I went to the path specified and found an old calibration image. I deleted, closed snapmaker luben, reopened and the calibration image reappeared in the tmp file. I do no think that the calibration image is saved locally, but on the machine (a350), I assume it grabs the information from the machine (a350) directly and loads a tmp image on the PC, running snapmaker. Is there a way to clear the snapmaker local cache or specifically the calibration image saved on the snapmaker?

Yep, the `calibration image` is saved on the fabsreen. U can redo the `calibration operation` on fabsreen to change `calibration image`.
