### ISSUE TITLE
Camera calibration needs additional cross for center image

### ISSUE THREAD

**Issue by helmut-steiner** [Snapmaker/Luban#840]
Hey,
Camera calibration works mostly fine except that the middle image is not aligned properly as there are no markers. This makes aligning a circular object in the middle error prone.

Camera calibration only has 4 lines which align the outer images:
![image](https://user-images.githubusercontent.com/8708898/110445313-42ee7f00-80be-11eb-883a-099fd84dd81a.png)
But the center image is not aligned properly, thus the dimensions are off:
![image](https://user-images.githubusercontent.com/8708898/110445332-47b33300-80be-11eb-97d3-b2949137d317.png)

My suggestion: Add 2 crossing lines (i.e. an X) in the center part for calibration.

**Comment by jane-rose** [comment]
Sorry, i don't think it is the point. It might be an exposure problem.
Could you please send me the source image of it so that we can troubleshoot it?
On your computer, check the images in a folder named "Tmp", and they are generated by the camera directly. You need to send us the jpg files with file names starting with 'img'. In this case, you can just look at the pic starting with 'img4_'.
And here is an image for your reference:

For Windows OS: C:\Users\admin\AppData\Roaming\snapmaker-luban\Tmp
admin is PC's username

For macOS: /Users/admin/Library/Application\ Support/snapmaker-luban/Tmp
admin is PC's username

**Comment by jane-rose** [comment]
Sorry, i don't think it is the point. It might be an exposure problem.
Could you please send me the source image of it so that we can troubleshoot it?
On your computer, check the images in a folder named "Tmp", and they are generated by the camera directly. You need to send us the jpg files with file names starting with 'img'. In this case, you can just look at the pic starting with 'img4_'.
And here is an image for your reference:

For Windows OS: C:\Users\admin\AppData\Roaming\snapmaker-luban\Tmp
admin is PC's username

For macOS: /Users/admin/Library/Application\ Support/snapmaker-luban/Tmp
admin is PC's username

**Comment by helmut-steiner** [comment]
I redid the calibration today and it is worse than before.
![image](https://user-images.githubusercontent.com/8708898/112188015-e7b2a580-8c02-11eb-815a-f8bec8d320d3.png)

Here are the files starting with "img" from the Tmp folder:
[Tmp.zip](https://github.com/Snapmaker/Luban/files/6191528/Tmp.zip)

**Comment by helmut-steiner** [comment]
I also tried using a white sheet of paper underneath to get a proper exposure but the stitching is way off.
![image](https://user-images.githubusercontent.com/8708898/112188809-9e168a80-8c03-11eb-9962-4fe106377ff3.png)

**Comment by jane-rose** [comment]
Using Camera Capture on objects with a certain height, the perspective distortion of the camera will cause the problem that the stitching does not seem to be connected. As this time, we may not solve this problem.

**Comment by sumibin** [comment]
Please try to use the height compensation mode in the new version, which is designed for this case.
